<template>
  <div class="container mx-auto p-4 md:p-6 lg:p-8 mt-16">
    <div class="bg-orange-100 p-6 text-center rounded-lg shadow-md mb-8">
      <h1 class="text-3xl md:text-4xl font-bold text-purple-700">Tambah Produk Baru ➕</h1>
      <p class="text-gray-600 mt-2">Tambahkan barang jualan Anda ke toko.</p>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6 border border-gray-200">
      <button @click="router.back()"
              class="inline-flex items-center px-4 py-2 bg-gray-200 text-gray-800 font-semibold rounded-lg shadow-md hover:bg-gray-300 transition duration-300 mb-6">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
        </svg>
        Kembali ke Dashboard
      </button>

      <form @submit.prevent="submitProduct" class="space-y-6">
        <div>
          <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Nama Produk:</label>
          <input type="text" id="name" v-model="productForm.name" required
                 class="shadow appearance-none border-2 border-purple-300 rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-300">
        </div>
        
        <div>
          <label for="description" class="block text-gray-700 text-sm font-bold mb-2">Deskripsi Singkat:</label>
          <textarea id="description" v-model="productForm.description" required
                    class="shadow appearance-none border-2 border-purple-300 rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-300 h-24"></textarea>
        </div>

        <div>
          <label for="descriptionFull" class="block text-gray-700 text-sm font-bold mb-2">Deskripsi Lengkap:</label>
          <textarea id="descriptionFull" v-model="productForm.descriptionFull"
                    class="shadow appearance-none border-2 border-purple-300 rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-300 h-32"></textarea>
          <p class="text-gray-500 text-xs mt-1">Opsional, deskripsi yang lebih detail untuk halaman produk.</p>
        </div>

        <div>
          <label for="price" class="block text-gray-700 text-sm font-bold mb-2">Harga (Rp):</label>
          <input type="number" id="price" v-model.number="productForm.price" required min="0"
                 class="shadow appearance-none border-2 border-purple-300 rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-300">
        </div>

        <div>
          <label for="stock" class="block text-gray-700 text-sm font-bold mb-2">Stok:</label>
          <input type="number" id="stock" v-model.number="productForm.stock" required min="0"
                 class="shadow appearance-none border-2 border-purple-300 rounded-lg w-full py-3 px-4 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-purple-300">
        </div>

        <button type="submit"
                class="w-full px-6 py-3 bg-purple-600 text-white font-semibold text-lg rounded-lg shadow-md hover:bg-purple-700 transition duration-300">
          Tambah Produk
        </button>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useProductStore, type Product } from '@/stores/product';
import { useUserStore } from '@/stores/user';

const router = useRouter();
const productStore = useProductStore();
const userStore = useUserStore();

// Form state
const productForm = ref({
  name: '',
  description: '',
  descriptionFull: '',
  price: 0,
  stock: 0,
});

const submitProduct = () => {
  const currentUser = userStore.getLoggedInUser;
  if (!currentUser) {
    alert('Anda harus login untuk menambahkan produk.');
    router.push('/login');
    return;
  }

  if (productForm.value.name.trim() === '' || productForm.value.description.trim() === '' || productForm.value.price <= 0 || productForm.value.stock < 0) {
    alert('Mohon lengkapi semua bidang yang wajib dan pastikan harga/stok valid.');
    return;
  }

  // Omit 'id' and 'status' as they are generated by the store
  const newProductData: Omit<Product, 'id' | 'status' | 'imageUrl'> = {
    name: productForm.value.name,
    description: productForm.value.description,
    descriptionFull: productForm.value.descriptionFull,
    price: productForm.value.price,
    stock: productForm.value.stock,
    sellerId: currentUser.id,
    sellerName: currentUser.username,
  };

  productStore.addProduct(newProductData);
  alert('Produk berhasil ditambahkan!');
  router.push('/user-dashboard?tab=my-products'); // Kembali ke dashboard tab produk saya
};
</script>

<style scoped>
.container {
  max-width: 800px;
}
</style>
